-- USER SQL
CREATE USER tm IDENTIFIED BY tm 
DEFAULT TABLESPACE JW
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER tm QUOTA UNLIMITED ON JW;

-- ROLES
GRANT RESOURCE TO tm;
GRANT CONNECT TO tm;