-- USER SQL
CREATE USER ea IDENTIFIED BY ea
DEFAULT TABLESPACE JW
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER ea QUOTA UNLIMITED ON JW;

-- ROLES
GRANT RESOURCE TO ea ;
GRANT CONNECT TO ea ;